export const allMonths = [
	'Styczeń',
	'Luty',
	'Marzec',
	'Kwiecień',
	'Maj',
	'Czerwiec',
	'Lipiec',
	'Sierpień',
	'Wrzesień',
	'Październik',
	'Listopad',
	'Grudzień',
]

export const allYears = Array.from({ length: 2044 - 2024 + 1 }, (_, i) => 2024 + i)

export const messages = [
	{ id: '01', message: 'Jesteś najlepsza i zawsze będę w Ciebie wierzyć!' },
	{ id: '02', message: 'Jesteś moją siłą i największym wsparciem.' },
	{ id: '03', message: 'Każdy dzień z Tobą to szczęście, którego nie da się opisać.' },
	{ id: '04', message: 'Kocham Cię bardziej, niż mogłabyś sobie wyobrazić.' },
	{ id: '05', message: 'Jesteś najpiękniejszym uśmiechem, jaki widziałem.' },
	{ id: '06', message: 'Twoja siła i dobroć są inspiracją dla mnie każdego dnia.' },
	{ id: '07', message: 'Jesteś wszystkim, czego potrzebuję, aby być szczęśliwy.' },
	{ id: '08', message: 'Zawsze będę przy Tobie, bez względu na wszystko.' },
	{ id: '09', message: 'Nie ma rzeczy, której byś nie pokonała. Jesteś nie do zatrzymania!' },
	{ id: '10', message: 'Każdego dnia kocham Cię jeszcze bardziej.' },
	{ id: '11', message: 'Nigdy nie zapominaj, jak wspaniała jesteś!' },
	{ id: '12', message: 'Twoje serce jest największym skarbem, jaki znam.' },
	{ id: '13', message: 'Jestem dumny, że jesteś częścią mojego życia.' },
	{ id: '14', message: 'Z Tobą każdy dzień jest lepszy od poprzedniego.' },
	{ id: '15', message: 'Kocham Cię za to, kim jesteś, i za to, kim dzięki Tobie się staję.' },
	{ id: '16', message: 'Twoja miłość sprawia, że czuję się najszczęśliwszym człowiekiem na ziemi.' },
	{ id: '17', message: 'Jesteś najpiękniejszym prezentem, jaki dało mi życie.' },
	{ id: '18', message: 'Jesteś moim światłem w każdej ciemności.' },
	{ id: '19', message: 'Jesteś cudowna dokładnie taka, jaka jesteś!' },
	{ id: '20', message: 'Jesteś powodem, dla którego wstaję z uśmiechem na twarzy.' },
	{ id: '21', message: 'Dasz sobie radę ze wszystkim, bo jesteś niesamowita!' },
	{ id: '22', message: 'Nie ma rzeczy, której nie moglibyśmy razem przezwyciężyć.' },
	{ id: '23', message: 'Nigdy nie przestawaj marzyć!' },
	{ id: '24', message: 'Każdego dnia przypominasz mi, czym jest prawdziwe szczęście.' },
	{ id: '25', message: 'Kocham Cię za milion rzeczy, których nawet nie da się opisać.' },
	{ id: '26', message: 'Dziękuję, że jesteś!' },
	{ id: '27', message: 'Zawsze wierzę w Ciebie i Twoje możliwości.' },
	{ id: '28', message: 'Jesteś moją najlepszą przyjaciółką i miłością mojego życia.' },
	{ id: '29', message: 'Twoje piękno rozświetla każdy dzień mojego życia.' },
	{ id: '30', message: 'Zawsze będziesz dla mnie najważniejsza.' },
	{ id: '31', message: 'Dziękuję, że jesteś moją miłością i najlepszym, co mnie spotkało.' },
]
